### ISSUE TITLE
Probably still some artifact left of libmuondetector-shared

### ISSUE THREAD

**Issue by hangeza** [MuonPi/muondetector#2]
Found the following line which may still reference to the old shared lib:
https://github.com/MuonPi/muondetector-cleaned/blob/296f9111cb1f70018d1cebe79867e933bb174215/source/library/CMakeLists.txt#L68
Pls check if this has to be removed or not.

**Comment by dtreffenstaedt** [comment]
The line is necessary for exporting and importing the library features as seen here:
https://github.com/MuonPi/muondetector-cleaned/blob/296f9111cb1f70018d1cebe79867e933bb174215/source/library/include/muondetector_shared_global.h#L7-L11

The name is misleading, I renamed the constant to MUONDETECTOR_LIBRARY_EXPORT in https://github.com/MuonPi/muondetector-cleaned/commit/0f63943ccaeb9d93a89f8df82734d3628be372f6
