### ISSUE TITLE
GUI does not connect and shows no error

### ISSUE THREAD

**Issue by alexschultze** [MuonPi/muondetector#23]
Pressing connect does not give any result, and no failure message why.
(Windows GUI client 2.0.0)
Command Window Output:

```
file open failed in 'ReadOnly' mode at location  "ipAddresses.save"
qrc:/qml/CustomMap.qml:72:17: QML Rectangle: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
qrc:/qml/CustomMap.qml:84:17: QML Rectangle: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
QObject::connect(QQuickWindow, MapComponent_QMLTYPE_5_QML_8): invalid nullptr parameter
QMetaObject::connectSlotsByName: No matching signal for on_doBiasCalibPushButton_clicked()
QMetaObject::connectSlotsByName: No matching signal for on_transferBiasCoeffsPushButton_clicked()
QGeoTileProviderOsm: Tileserver disabled at  QUrl("http://maps-redirect.qt.io/osm/5.8/satellite")
QGeoTileFetcherOsm: all providers resolved
```

**Comment by hangeza** [comment]
This is (or at the time when the development on the GUI started, was) indeed the intended behavior. When no link for the selected address can be established, nothing happens, i.e. the controls and value displays are not becoming active. But there is no error message either, which is imho fine, when one knows how a successfully established connection looks like.
However, not showing any result at all might be confusing for users who are trying to initially set up their detectors and therefore are left with an obstructed troubleshooting; they simple wouldn't know what to expect.

We'll leve this issue open for the MuonPi developers to implement an indication about connection failure (an indication for connection success does already exist) in the GUI program.

**Comment by dtreffenstaedt** [comment]
Added in commit https://github.com/MuonPi/muondetector/commit/a2fb606e29b1030d6f6b3f9106a5a0ea3fe2b726 for version v2.0.2
