### ISSUE TITLE
Make config file more versatile

### ISSUE THREAD

**Issue by marvin5300** [MuonPi/muondetector#34]
Think about more features that should be in the config file for the daemon.
- select tcp port
- select local storage on or off

**Comment by dtreffenstaedt** [comment]
Also maxGeohashLength

**Comment by dtreffenstaedt** [comment]
has been implemented with https://github.com/MuonPi/muondetector/commit/3982ad6421fd9428d748b59d3316c79c48e13b32

**Comment by dtreffenstaedt** [comment]
Configuration is not loaded properly, needs to be checked again.

**Comment by dtreffenstaedt** [comment]
Should be fixed with https://github.com/MuonPi/muondetector/commit/6c65e27b3a841b375410a5ebc1735c7d0a2f292c
