### ISSUE TITLE
Create a spreadsheet about used ressources

### ISSUE THREAD

**Issue by marvin5300** [MuonPi/muondetector#35]
spreadsheet should include:
- used ports (TCP 51508 for daemon, TCP 8888 for pigpiod)
- used optional components (pigpiod ... )
- whole list of configuration parameters
- cpu, gpu, ram benchmark (maybe?)

**Comment by SimonGLM** [comment]
Work in Progress: [Resource usage](https://wiki.muonpi.org/index.php?title=Resource_usage)
Feel free to contribute!
