### ISSUE TITLE
'could not open login data save file' when running login script

### ISSUE THREAD

**Issue by marvin5300** [MuonPi/muondetector#38]
**Describe the bug**
Login script not working when running before first start of daemon.

**To Reproduce**
Freshly installed muondetector software.
Run login script before first time start of daemon.

**Expected behavior**
Login should be successful.

**Additional context**
Folder with cryptic name (Hashed MAC-Address) gets created at first start of daemon. This folder does not exist before.
Login script expects it to be there and can't open file inside it.
Fix: Create this folder in login program if not exists.
Or: Reconsider all folder structure in daemon when changing how data is saved on disk.

**Comment by dtreffenstaedt** [comment]
I would prefer a careful consideration about how the filesystem structure is laid out in the future.

However, when already doing this, it would be beneficial to implement this in a reworked muondetector-init program which does not only handle authentication but also general setup of the RaspberryPi.
