### ISSUE TITLE
Checkbox "Peak Det Hi Gain" not working in Parameters Tab of GUI

### ISSUE THREAD

**Issue by oe5hcl** [MuonPi/muondetector#45]
**Describe the bug**
The Checkbox "Peak Det Hi Gain" is not working in the Tab Parameters of the GUI. Also there is no effect on the GPIO Pin of the RaspberryPi. 
The Checkbox "High Gain" in the tab "Overview" is working and has effect on the GPIO Pin of the RaspberryPi.

**To Reproduce**
Toggle the Checkbox in the Tab Parameters and measure the voltage of the HI_GAIN Pin. The voltage level does not change. Toggle the Checkbox "High Gain" in the tab "Overview". The voltage level changes between 0V and 3V3.

**Expected behavior**
Both Checkboxes should have the same behavior. Also the Checkbox should have the same labeling.

**Comment by hangeza** [comment]
closed with PR #46
