### ISSUE TITLE
Pulse Height Histogram in GUI should be deactivated by default

### ISSUE THREAD

**Issue by oe5hcl** [MuonPi/muondetector#49]
As long as very few users have a peak detector, the pulse height histogram should be deactivated by default when connecting the GUI.
The display of the Historgram without the Peak Detector is confusing for new users and could be interpreted as an error.

**Comment by dtreffenstaedt** [comment]
FIxed with https://github.com/MuonPi/muondetector/commit/2305d6d8f2b69199ec687c2c3f963d34edc0bcb3 . Will be in version 2.0.2.
