### ISSUE TITLE
Emit uniqueId from daemon every day

### ISSUE THREAD

**Issue by dtreffenstaedt** [MuonPi/muondetector#55]
Currently the eeprom uniqueId is only sent on daemon start.

It would be better if it was also emitted every day, maybe together with the threshold levels.

A different name would also not be bad, uniqueId is ambiguous, I suggest something along the lines of `eepromUID`.

**Comment by hangeza** [comment]
Actually, the log parameters with the LOG::ONCE property are emitted at daemon restart AND at log rollover which appears every 24 hours.

**Comment by dtreffenstaedt** [comment]
Alright, perfect.
