### ISSUE TITLE
problems with installing qt5-default dependencies

### ISSUE THREAD

**Issue by kimbou** [MuonPi/muondetector#69]
**Describe the bug**
When installing the qt5-default dependency for the code, i get the error that the package is not available, but is referred to by another package. This seems to be because qt5-default is no longer included with Ubuntu 21.04. 
This issue can be fixed by installing the base packages manually as described here: 

https://stackoverflow.com/questions/67373586/install-qt5-on-ubuntu-21-04

**Comment by hangeza** [comment]
Thanks for this hint! The cheat-sheet for installing the prerequisites is now adapted based on the suggested stackoverflow solution.
