### ISSUE TITLE
Implement position model to allow dense detector arrays

### ISSUE THREAD

**Issue by hangeza** [MuonPi/muondetector#7]
**Scope**
Primarily muondetector-daemon, for accessibility and monitoring also muondetector-gui

**Description**
Currently, the geographic coordinates of a detector station are determined by sending the mean of the coordinates from continuous GNSS fixes over a one-minute interval (MUONPI_LOG_INTERVAL_MINUTES in config.h) through log messages to the server. Therefore, these short-time fixes may wander around over several meters or even more depending on the GNSS reception. This scheme can not be used for the Time-of-Flight (ToF) reconstruction of showers in dense close-vicinity constellations of detectors. A fixed geometrical arrangement with relative positions to one precise reference coordinate is required for this purpose.

**Proposition**
In order to accomodate for the dense-detector arrangement with the (hardware-)unmodified MuonPi detectors, the geographic coordinates reported by each station could be altered. For this end, the following proposition is made:

Introduce a GNSS fix mode which may assume several states: 
- auto mode which determines and reports the position as it is currently done (default).
- static mode, where a fixed set of geo coordinates is provided (eg. from config file and/or the GUI). Then this set of coordinates is logged and published instead of the GNSS fixes
- lock-in mode, where the daemon accumulates all fixes over a specified measurement interval (LOCK_IN_MEASUREMENT_INTERVAL probably to be set in config.h) on the order of typically a day. In the measurement phase, the fixes are only accepted and stored to the accumulation buffer, if a limiting fix precision is kept (e.g. LOCK_IN_FIX_LIMIT_GEO,  LOCK_IN_FIX_LIMIT_TIME, LOCK_IN_FIX_LIMIT_DOP in config.h or something of that kind). In the end of the lock-in phase, the mean (median?) of all coordinates is assumed to be the most precise determination of the station's position and overrides the static geo coordinates. Those will from then on be reported like in static mode.

With the static or lock-in mode activated, each station may fix it's position more accurate than in free-floating auto mode. For dense detector arrays, however the static mode would seem more preferable. Setting the coordinates for each station could then be aleviated by a small add-on in the GUI, where the station's coordinates can be calculated and set by specifying a reference coordinate and a relative geometric offset.

Any more ideas or proposals on this?

**Comment by SimonGLM** [comment]
PR #90 includes this feature.
It's in the timeline for release v2.1.0
