### ISSUE TITLE
Unreadable labels on macOS "dark theme"

### ISSUE THREAD

**Issue by CodingBobby** [MuonPi/muondetector#74]
When setting the native system theme of macOS (10.14) to "dark", the GUI does automatically adapt the colours, which works fine, except in places where the background-colour is fixed to white. As the text-colour changes to white for the dark theme, the labels and ticks of plot axes render unreadable.

Here are two screenshots of the GUI (version 2.0.2 installed from [this release](https://github.com/MuonPi/muondetector/releases/tag/v2.0.2)) comparing the macOS themes "bright" and "dark":

![Bildschirmfoto 2022-05-02 um 13 36 10](https://user-images.githubusercontent.com/30275177/166227576-957cef05-50de-49e1-ba6c-cdaceab8ca2e.png)

![Bildschirmfoto 2022-05-02 um 13 35 20](https://user-images.githubusercontent.com/30275177/166227609-83388952-69b7-43b6-a0bd-f0d3bf63ce0b.png)

A solution would be to fix the text-colour to black wherever the background-colour is fixed to a bright colour (notice that the boxes for time pulse and MQTT connection statuses are also barely readable). This wouldn't affect the bright theme or any other system that has no native dark theme.

**Comment by hangeza** [comment]
The issue seems to be fixed for the time being with PR #75. However, it would be nice if also the Qwt widgets would follow the system-wide applied theme and switch to e.g. dark background when dark theme is selected. Is there any chance that this could be realized?

**Comment by hangeza** [comment]
With commit 86c8a030fb6de14b89771c7f14f35fd4b6178b76 all widgets should now adjust automatically to the currently selected color theme. Tested under Linux Mint 20.3 (Una) and MATE desktop. Plz. reopen issue in case there are still some problems with this in your environment
![Screenshot](https://user-images.githubusercontent.com/40604124/166562882-66f68e5c-c036-4377-bc06-68c42f26677a.png)
![Screenshot](https://user-images.githubusercontent.com/40604124/166563135-086e0376-a92a-4f47-bfae-f21cc5d31f2a.png)
![Screenshot](https://user-images.githubusercontent.com/40604124/166563261-f776a8e5-20c3-45ae-ae2d-85e83c22de40.png)
.
